version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/chickenmayo
    overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: script/deploy.sh
      timeout: 180
      runas: root