version: 0.0
os: linux

files:
  - source: /
    destination: /mnt/chickenmayo

permissions:
  - object: /mnt/chickenmayo
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: root