name: CI Build

on:
  push:
    branches: [feature/SLUB-60]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #      # 소스를 가져온다
      #      - name: Checkout cod
      #        uses: actions/checkout@v2

      # 실행 속도를 빠르게 하기위해 설치된 Node 모듈을 캐시하도록 설정한다.
      #      - name: Cache node modules
      #        uses: action/cache@v2
      #        with:
      #          path: ~/.npm
      #          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #          restore-keys: |
      #                        ${{ runner.os }}-node-

      # Node 14.x를 사용한다.
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: npm install
        run: npm install

      - name: run test code
        run: npm run test:watch

      - name: if fail
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{ github.token }}
          script: :|
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body:"테스트코드를 다시 확인해주세요. ",
              event:"REQUEST_CHANGES"
            })
            await github.pulls.update({
              ...context.repo,
              pull_number,
              state:"closed"
            })
          if: failure()


#
#      # 모듈을 설치한다.
#      - name: Install packages
#        run: npm ci
#
#      # 결과물을 만든다.
#      - name: Build
#        run: npm run build
#
#      # S3에 결과물을 업로드한다.
