name: CI Build

on:
  push:
    branches: [feature/SLUB-60]
  pull_request:
    branches: [master]

env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install

      - name: Build                   # React Build
        run: npm run build
        env:
          CI: ""

      - name: Make zip file           # build 내용 zip 파일 압축
        run: zip -qq -r./build-fe.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION : ${{ secrets.AWS_REGION }}

      - name: Upload to S3            # S3 버킷 /react-front build 파일 업로드
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION : ${{ secrets.AWS_REGION }}
        run: | 
          aws s3 cp --region $AWS_REGION ./build-fe.zip s3://$S3_BUCKET_NAME/react-front/./build-fe.zip
#        run: aws s3 cp --recursive --region $AWS_REGION build s3://$S3_BUCKET_NAME # 정적 페이지 업로드시

      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name slub
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name frontend-react-master
          --s3-location bucket=$S3_BUCKET_NAME,key=react-front/./build-fe.zip,bundleType=zip

